#!/usr/bin/env python

from platform_methods import run_in_subprocess
import lua_codes_builders

Import("env")
Import('env_modules')

lua_templates = Glob("templates/*/*.lua")
make_lua_templates_builder = Builder(
    action=run_in_subprocess(lua_codes_builders.make_lua_templates), suffix=".h", src_suffix=".lua"
)
env["BUILDERS"]["MakeLuaTemplateBuilder"] = make_lua_templates_builder
env.Alias("lua_templates", [env.MakeLuaTemplateBuilder("#modules/lua_templates.gen.h", lua_templates)])

env_luascript = env_modules.Clone()

# if not env.msvc:
#     env_luascript['CXXFLAGS'] = ['-std=c++17']
# else:
#     env_luascript['CCFLAGS'] = ['/std:c++17','/Zc:__cplusplus']
#     env_luascript.Append(CPPDEFINES=['ANTLR4CPP_STATIC'])

Export('env_luascript')

SConscript('lib/lua/SCsub')
SConscript('wrapper/SCsub')
if env.editor_build:
    SConscript('editor/SCsub')

env_luascript.add_source_files(env.modules_sources,'*.cpp')
