#!/usr/bin/env python

Import("env")
Import("env_modules")
env_opengl3 = env_modules.Clone()

env_opengl3.add_source_files(env.modules_sources, "*.cpp")
env_opengl3.add_source_files(env.modules_sources, "storage/*.cpp")
