#!/usr/bin/env python

Import("env")
Import("env_modules")

env_filesystem_server = env_modules.Clone()

env_filesystem_server.add_source_files(env.modules_sources, "*.cpp")
env_filesystem_server.add_source_files(env.modules_sources, "providers/*.cpp")

if env.editor_build:
    env_filesystem_server.add_source_files(env.modules_sources, "editor/*.cpp")
