#!/usr/bin/env python

Import("env")
Import('env_modules')

env_configuration = env_modules.Clone()

env_configuration.add_source_files(env.modules_sources,'*.cpp')

if env.editor_build:
    env_configuration.add_source_files(env.modules_sources,'editor/*.cpp')
