#!/usr/bin/env python

import os
import inspect
import spike_methods

Import("env")
Import("env_modules")

env["BUILDERS"]["MakeSpikeLicenseHeader"] =  Builder(
    action=env.Run(spike_methods.make_spike_license_header, "Genarate spike license header."),
    suffix = ".h",
    src_suffix = ".lic"
)
env.Alias("spike_license", [env.MakeSpikeLicenseHeader("#modules/spike_license.gen.h", Glob("../*/*.lic"))])

env_spike = env_modules.Clone()

env_spike.add_source_files(env.modules_sources, "*.cpp")
env_spike.add_source_files(env.modules_sources, "servers/*.cpp")
env_spike.add_source_files(env.modules_sources, "string/*.cpp")

if env.editor_build:
    env_spike.add_source_files(env.modules_sources, "editor/*.cpp")
    env_spike.add_source_files(env.modules_sources, "editor/*/*.cpp")

print("Generating spike version header...")
spike_methods.generate_spike_version_header(env.module_version_string)
